codemeta/codemeta

- crosswalk.csv
Greetings,
I added columns for DataCite and Dublin Core metadata schemas to the crosswalk. DataCite has already been discussed (issue #13), and I definitely agree that it's a good idea. Dublin Core is pretty trivial, but I think that it could be useful for getting software into researcher's normal manuscript-writing workflow (e.g., facilitating import into reference managers).
> add DataCite and Dublin Core to crosswalk

- example-codemeta.json
Very small issue - example-codemeta.json wasn't actually valid json because of the comma on L35. Running the example JSON through the [JSON-LD playground](http://json-ld.org/playground/) or any JSON validator wouldn't work.
@mbjones
> Make codemeta example JSON valid

- crosswalk.csv
From here:
http://rrr.cs.st-andrews.ac.uk/wp-content/uploads/2015/10/guidelines-software-identification.pdf
This is a DataCite-based schema to represent software. It's slightly different than the existing column for Datacite which is why I added it.
Note that this is a partial map as some of the concepts don't appear to be present in CodeMeta.
> Add the Software Entities Model

- codemeta-crosswalk.md
Is DOAP unknown to this community? Thought it would be good to flag it as an interop target and as prior art.
A related (but long stale) project is https://github.com/gkellogg/github-lod
> Add DOAP to un-crosswalked schemas

- .travis.yml
- Gemfile
- Rakefile
- example-codemeta-agent.json
- minitest/test_example_codemeta.rb
- minitest/test_example_codemeta_agent.rb
Adds an initial test for the agent example file. Note that this test currently fails, as the file is not valid JSON.
Moves the test script into a Rake task to handle multiple minitest files.
> Add test for Agent example

- README.md
When you click "mappings" you get a 404 at https://github.com/codemeta/codemeta/blob/master/codemeta-crosswalk.md 
By the way, I got here because I'm thinking about describing software projects over at https://github.com/IQSS/open-source-at-harvard/issues/3 and feedback there is quite welcome!
> link to crosswalk.csv rather than codemeta-crosswalk.md (404)

- README.md
Hello!
I noticed that `...cite the CodeMeta schema and project as:` trails off into the next heading. Maybe the quote block got shifted upwards before it was initially committed? Since I [found no commit to revert this disconnect](https://github.com/codemeta/codemeta/blame/fc4310326054b6307b48b24176569ea175fcaad1/README.m), here is a simple fix suggestion that seems logical to me. In case something else should be done to close the sentence, please let me know.
Cheers :-)
> close "You can cite..." sentence logically

- crosswalk.csv
> Corrected spelling of dateCrated

- codemeta.json
Add funder field to example codemeta file and make it clearer that funding is for specific grant number and title information.  I'm not sure how we'd handle multiple funders and grant numbers - Ideally it would be better to have funding (grant info) be a subset of funder (like DataCite).
> Better example of funder and funding types

- codemeta.json
'softwareVersion' is only for SoftwareApplication, not for SoftwareSourceCode
> Use 'version' instead of 'softwareVersion' in codemeta.json

- crosswalks/NodeJS.csv
"engines" is for interpreters, not CPUs: https://docs.npmjs.com/files/package.json#engines
> NodeJS: Move 'engines' from processorRequirements to runtimePlatform.

- crosswalks/Java (Maven).csv
In Maven metadata, 'repositories' is used to fetch binary dependencies.
'scm' is closer to the meaning of codeRepository.
https://maven.apache.org/pom.html#SCM
https://maven.apache.org/pom.html#Repositories
> Java/Maven: Add SCM key to codeRepository

- codemeta.json
looks like the rename from https://github.com/codemeta/codemeta/pull/201/ accidentally created a duplicate. The other ``version`` is at line 10:
https://github.com/codemeta/codemeta/blob/18b248d9cf492d078ef6d2dde115e1aa137bbcdb/codemeta.json#L10
> removed duplicate key 'version'

- crosswalk.csv
- properties_description.csv
To be consistent with the declaration in codemeta.jsonld, datePublished in this same file, and https://github.com/codemeta/codemeta.github.io/commit/1a748e64fcd44506a116cff95f27f24748873557
(I didn't realize codemeta.github.io was generated from this repo)
> Disallow DateTime for dateCreated and dateModified

- crosswalks/R Package Description.csv
The "Version" field of the R Package DESCRIPTION aligns with both the "softwareVersion" and "version" concepts of CodeMeta and inherited from "SoftwareApplication" and "CreativeWork", respectively. Generally, "softwareVersion" is preferred over "version" as the former is inherited from the more specific "SoftwareApplication" type as opposed to the more general "CreativeWork".
NOTE: "softwareVersion" is typed text only, whereas "version" is typed to be either numeric or text. Also, the "softwareVersion" concept seems to be less frequently used than "version".
> Update R Package Description.csv

- codemeta.jsonld
https://codemeta.github.io/terms/ documents it as "Text or URL" (like schema.org), but
`"@type": "@id"` means only URLs are allowed.
> Remove type restriction of "releaseNotes"

- crosswalks/Wikidata.csv
issue tracker URL (P1401) https://www.wikidata.org/wiki/Property:P1401 is the wikidata property associated with issue tracking
> [wikidata] Replace issue tracker URL

- properties_description.csv
- Line 60 and 62: Add quotes around the last field (which contains a comma `,` that can confused CSV parser and thought that the rows have 5 columns instead of 4)
- Line 61: `roleName` should be `Text or URL` (currently it has Text followed by URL - `Text,URL`, which also make it 5 columns)
By fixing these column number inconsistencies, GitHub will able to display the file as a table.
- Line 65, 66, 70, 72: Capitalizes first character in the sentence.
- Put "a" determiner for "link", make it "a link" just as "a license", "a flag", etc. as appeared in other property descriptions.
- Replace double spaces with single spaces
> Fix CSV column inconsistency and roleName type

- README.md
- Update URL and badge to use https://w3id.org/codemeta/3.0
- Also make Markdown style more consistent
- Headings were mixed of === and ## --> Use only ##
- Bullet lists were mixed of * and - --> Use only - (dash)
- Strong text were mixed of ** and __ --> Use only __ (2 underscores)
> Update purl badge to 3.0 in README.md

- CONTRIBUTORS.MD
- Add @ to those GitHub usernames without
- Add GitHub username text label to bare links (in V2.0 list)
- Replace `http://` links with `https://`
- Fix broken links
- Remove extra spaces
- Use same date format across the document
- Add Post-V3.0 contributors for crosswalks contributors
- dgarijo for #327
- progval and bandrow for #331
- bact for #344
> Update CONTRIBUTORS.MD - make consistency

- crosswalks/VIVO.csv
Adds crosswalk between codemeta and the VIVO ontology software class and its object and data properties.
The VIVO.csv file which is describing the crosswalk. The second column besides the name of object/data property, specify  object/data  property URIs and range. Moreover, if some mapping is more complex and include more elements from the graph dot is used as separator in the following syntax:
funder, informationResourceSupportedBy.assignedBy (property URI - http://vivoweb.org/ontology/core#informationResourceSupportedBy; http://vivoweb.org/ontology/core#assignedBy; range URI - http://vivoweb.org/ontology/core#Grant; http://xmlns.com/foaf/0.1/Organization)
This mean information about funder organization might be found starting from a Software class through its object properties …
> VIVO crosswalk
