- crosswalk.csv
Added SoftwareContributor, Publisher, Relationship, InteractionMethod,
ProgrammingLanguage. Updated the Software Entities Model accordingly. The other entries already in the table were not updated
See #28 for my justification. InteractionMethod is meant to capture the way the user interacts with the software (service, CLI, API etc)
> Added some concepts to the crosswalk

- .gitignore
- .travis.yml
- Gemfile
- test/validate.rb
This simply tests that the example file parses as JSON-LD and yields a graph with at least one triple.
> Add a very minimal CI

- .travis.yml
Travis wants to use 1.9 which is long deprecated.
> Use Ruby 2.3 for CI

- tools.md
This page is the beginning of a list of available tools for CodeMeta to provide a starting point for people who are new to the project and to list existing tools to either provide access or a jumping off point for think about using CodeMeta and building new tools.
> Tools page for the CodeMeta project

- CONTRIBUTORS.MD
I would estimate that ~50% of all pull requests I make include this edit 😆
> Github -> GitHub typo fix.

- crosswalk.csv
This PR adds the [Citation File Format](https://github.com/citation-file-format/citation-file-format) mapping to crosswalk.csv.
> Add Citation File Format mapping

- crosswalk.csv
The fixes for distutils are to move `url` from the `codeRepository` to the `url` one, and add `download_url`.
Sources:
* https://www.python.org/dev/peps/pep-0314/
* https://docs.python.org/3/distutils/setupscript.html#additional-meta-data
> Add 'Python PKG-INFO' + fixes to 'Python Distutils'.

- crosswalks/Ruby Gem.csv
https://guides.rubygems.org/specification-reference/#authors=
> Add 'authors' to the Ruby crosswalk.

- crosswalks/NodeJS.csv
https://docs.npmjs.com/files/package.json#people-fields-author-contributors
> NodeJS: Rename key 'contributor' to 'contributors'.

- crosswalks/Java (Maven).csv
https://maven.apache.org/pom.html#Issue_Management
> Java/Maven: Rename issuesManagement to issueManagement

- crosswalks/ASCL.csv
In ASCL the codemeta.json is available: https://ascl.net/1909.014/codemeta.json
From which we can understand better the mapping to the properties on the software record page:
https://ascl.net/1909.014/
and in the submission form: https://ascl.net/submissions
> Update ASCL crosswalk

- scripts/split.py
This the script changes in https://github.com/codemeta/codemeta/pull/251 by @tmorrell
> split.py: add support for running in differents CWDs

- CONTRIBUTORS.MD
Updated contributors file with PMC and contributors by version
> Update contributors for v2.1

- README.md
Update version with authors and identifier.
> Add v3.0 to README.md

- codemeta.json
We forgot to do this before tagging v3.0
> Update version in codemeta.json to v3.0

- README.md
Add information about CodeMeta governance model and people in `Organizers` section.
> Update README.md with governance model

- crosswalks/Wikidata.csv
describedBySource seems to be a reasonable equivalent to referencePublication
> Add reference publication equivalent

- crosswalks/Java (Maven).csv
looks like this got closed when the crosswalk branch was deleted
> update maven crosswalk

- crosswalks/BibTeX.csv
> Add BibTeX mapping

- CONTRIBUTORS.MD
Add these contributors to the Post-3.0 contributors list:
- @physikerwelt from #351
- @hjonin from #363
- @BaptisteCecconi from #367
> Add more post-3.0 contributors to CONTRIBUTORS.MD

- README.md
> README: Fix links to v3.0 schema

- codemeta.json
Update the repo codemeta file for v3
Replacement for https://github.com/codemeta/codemeta/pull/337
> Add PMC, update date, and URL

- CONTRIBUTING.md
The instructions for contributing a new mapping/editing an existing one were a bit sparse. I've updated them to specify the steps you have to take to arrive at a point where you can create a pull request. Some of the detail may seem really obvious to some people but I had to get help from someone else to create a pull request for the mapping I've just made so I'm sure that I'm not the only one.
> Updated CONTRIBUTING.md with more detailed instructions
